FROM nginx:stable
  # support running as arbitrary user which belogs to the root group
  RUN chmod g+rwx /var/cache/nginx /var/run /var/log/nginx
  EXPOSE 8181
  RUN rm /etc/nginx/conf.d/default.conf
  COPY configuration/nginx.config /etc/nginx/conf.d/default.conf
  # comment user directive as master process is run as user in OpenShift anyhow
  RUN sed -i.bak 's/^user/#user/' /etc/nginx/nginx.conf
  COPY static /usr/share/nginx/html
